-- Migration 032: Add hero content positioning columns (image overlays, typographic title, presentation text/image) for responsive controls.
-- These columns store the CMS-edited position/scale of hero content per device (desktop/tablet/mobile).

alter table public.offering_public_hero_settings
  add column if not exists title_image_scale numeric(4,2) not null default 1,
  add column if not exists title_image_scale_tablet numeric(4,2) not null default 1,
  add column if not exists title_image_scale_mobile numeric(4,2) not null default 1,
  add column if not exists title_image_position_x text not null default '50%',
  add column if not exists title_image_position_y text not null default '50%',
  add column if not exists title_image_position_x_tablet text not null default '50%',
  add column if not exists title_image_position_y_tablet text not null default '50%',
  add column if not exists title_image_position_x_mobile text not null default '50%',
  add column if not exists title_image_position_y_mobile text not null default '50%',
  add column if not exists title_image_secondary_scale numeric(4,2) not null default 1,
  add column if not exists title_image_secondary_scale_tablet numeric(4,2) not null default 1,
  add column if not exists title_image_secondary_scale_mobile numeric(4,2) not null default 1,
  add column if not exists title_image_secondary_position_x text not null default '50%',
  add column if not exists title_image_secondary_position_y text not null default '50%',
  add column if not exists title_image_secondary_position_x_tablet text not null default '50%',
  add column if not exists title_image_secondary_position_y_tablet text not null default '50%',
  add column if not exists title_image_secondary_position_x_mobile text not null default '50%',
  add column if not exists title_image_secondary_position_y_mobile text not null default '50%',
  add column if not exists hero_title_position_y text not null default '50%',
  add column if not exists hero_title_position_y_tablet text not null default '50%',
  add column if not exists hero_title_position_y_mobile text not null default '50%',
  add column if not exists hero_title_scale numeric(4,2) not null default 1,
  add column if not exists hero_title_scale_tablet numeric(4,2) not null default 1,
  add column if not exists hero_title_scale_mobile numeric(4,2) not null default 1,
  add column if not exists presentation_text_position_x text not null default '8%',
  add column if not exists presentation_text_position_y text not null default '50%',
  add column if not exists presentation_text_position_x_tablet text not null default '8%',
  add column if not exists presentation_text_position_y_tablet text not null default '50%',
  add column if not exists presentation_text_position_x_mobile text not null default '8%',
  add column if not exists presentation_text_position_y_mobile text not null default '50%',
  add column if not exists presentation_text_scale numeric(4,2) not null default 1,
  add column if not exists presentation_text_scale_tablet numeric(4,2) not null default 1,
  add column if not exists presentation_text_scale_mobile numeric(4,2) not null default 1,
  add column if not exists presentation_image_position_x text not null default '70%',
  add column if not exists presentation_image_position_y text not null default '50%',
  add column if not exists presentation_image_position_x_tablet text not null default '70%',
  add column if not exists presentation_image_position_y_tablet text not null default '50%',
  add column if not exists presentation_image_position_x_mobile text not null default '70%',
  add column if not exists presentation_image_position_y_mobile text not null default '50%',
  add column if not exists presentation_image_scale numeric(4,2) not null default 1,
  add column if not exists presentation_image_scale_tablet numeric(4,2) not null default 1,
  add column if not exists presentation_image_scale_mobile numeric(4,2) not null default 1;